### ISSUE TITLE
Rendering stylesheet

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iso690xml#2]

**Comment by opoudjis** [comment]
Won't do this as xslt, because life is too short: will do nokogiri script as reference implementation

**Comment by ronaldtse** [comment]
So what’s the next step here?

**Comment by opoudjis** [comment]
I'm creating a gem that renders bibitems in HTML: iso690render

**Comment by ronaldtse** [comment]
It sounds like it should be called “relaton-html”?

**Comment by ronaldtse** [comment]
As a counterpart to `isodoc` which generates HTML from Metanorma XML, they should be named similarly.

P.S. Isn't this the code we have in `relaton-cli`??

**Comment by opoudjis** [comment]
Not at all. relaton-cli is rendering just the title. This is about rendering bibliographic citations, with all their italics and embedding.

**Comment by ronaldtse** [comment]
But we could use the same code to generate the index as well, right? Using generic relaton for rendering an index would be immensely useful. This way generic relaton-html could render both index entries and citations.

BibItem also contain the links to the texts (HTML, PDF, etc). And the Abstract, and Authorship info is useful on the index, too.

Using relaton-html, we could render:
* a relaton collection in HTML
* a relaton entry in HTML

For example, we can even create an HTML page using a Relaton XML entry like this:
* https://www.iso.org/standard/61710.html

Again we need to ensure that the styling and citation formatting (i.e. presence and order of data elements) are separate issues.

I'd suggest we move the existing rendering code from relaton-cli into relaton-html and have relaton-cli link to relaton-html to achieve this.

**Comment by opoudjis** [comment]
This code will end up inside relaton. It will be used to render NIST references.

The strategy of 1 class = 1 gem can f* off. I'm sick of proliferating gems.

Gems will override rendering choices made here, so this code needs to be reasonably granular.

**Comment by opoudjis** [comment]
This is meant to be a generic renderer for everything in iso690, and that remains low priority (which means I will never get to it). If I ever do get to it, it will still be part of relaton.

**Comment by opoudjis** [comment]
NIST render.rb has substantially rewritten and debugged this, although it has also imposed its own rendering choices. This code should be treated as obsolete, and any future rendering of bibliographies should be based on NIST render.rb. A CSL solution to rendering is much more than I'm prepared to work on.

**Comment by ronaldtse** [comment]
This gem should be subsumed into Relaton for rendering Relaton references. Relaton should be able to be rendered as CSL too.

**Comment by opoudjis** [comment]
Work far, far in the future, and it won't be this gem any more, it will be NIST render.rb.

CSL? Hire more people.
