### ISSUE TITLE
Review current draft and model

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/iso690xml#3]

**Comment by ronaldtse** [comment]
The updated model looks good to me, we should merge this back to the Relaton models.

**Comment by ronaldtse** [comment]
@opoudjis looks like we can just replace the bib-models one with all the content from this one, except that in the grammar we need to add back `date_on`. Correct?

**Comment by opoudjis** [comment]
I think so. If you read the draft, I had doubts about a couple of attributes, but the bulk should be unaffected.
